---
github: toby3d
patreon: toby3d
open_collective: toby3d
ko_fi: toby3d
#tidelift: "platform-name/package-name"
#community_bridge: "project-name"
liberapay: toby3d
#issuehunt: "username"
#otechie: "username"
custom:
  - https://toby3d.me/pay/
  - https://toby3d.ru/pay/
