---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: golang
  commands:
  - go test -v -cover -race ./...
  volumes:
  - name: deps
    path: /go

- name: lint
  image: golangci/golangci-lint
  commands:
  - golangci-lint run ./...
  failure: ignore
  volumes:
  - name: deps
    path: /go

volumes:
- name: deps
  temp: {}
